### ISSUE TITLE
ImportError: cannot import name 'Index1D' from 'anndata.compat'

### ISSUE THREAD

**Issue by anishchakka** [lilab-bcb/cirrocumulus#208]
**Describe the bug**
Error while deploying cirro to server after updating to v1.1.57

**To Reproduce**
I had previously installed v1.1.54 cirro and updated the version to 1.1.57. This update does not deploy the app on server.

Command I had used to deploy:

`cirro serve -b server:8443 &`

**Expected behavior**
The same steps worked with v54. It failed with v57.

**Screenshots**

Below is the error I received.
```
ImportError: cannot import name 'Index1D' from 'anndata.compat' (/home/svc_bicore/miniconda3/envs/cirro_8443_clone/lib/python3.9/site-packages/anndata/compat/__init__.py)
[2023-12-18 12:52:57 -0800] [9330] [INFO] Worker exiting (pid: 9330)
Traceback (most recent call last):
  File "/home/miniconda3/envs/cirro_8443_clone/bin/cirro", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/cirro_8443_clone/lib/python3.9/site-packages/cirrocumulus/__main__.py", line 20, in main
    cmd.main(command_args)
  File "/home/miniconda3/envs/cirro_8443_clone/lib/python3.9/site-packages/cirrocumulus/serve.py", line 146, in main
    subprocess.check_call(run_args)
  File "/home/miniconda3/envs/cirro_8443_clone/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gunicorn', '-b', 'server:8443', '-w', '16', '-t', '30', '-n', 'cirrocumulus-webserver', 'cirrocumulus.serve:cached_app()']' returned non-zero exit status 1.
^C
```

**Desktop (please complete the following information):**

- OS: CentOS

**Comment by joshua-gould** [comment]
Please upgrade `anndata` (`pip install --upgrade anndata`). Thanks.
